"""empty message

Revision ID: 3de761880e00
Revises: 
Create Date: 2020-03-27 16:41:17.052952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de761880e00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cashflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Debt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Balancesheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('debt_id', sa.Integer(), nullable=True),
    sa.Column('cashflow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cashflow_id'], ['Cashflow.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['debt_id'], ['Debt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cash', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=True),
    sa.Column('cashflow_id', sa.Integer(), nullable=True),
    sa.Column('balancesheet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['balancesheet_id'], ['Balancesheet.id'], ),
    sa.ForeignKeyConstraint(['cashflow_id'], ['Cashflow.id'], ),
    sa.ForeignKeyConstraint(['debt_id'], ['Debt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Account')
    op.drop_table('Balancesheet')
    op.drop_table('Debt')
    op.drop_table('Cashflow')
    # ### end Alembic commands ###
